// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddBug: typeof import('./components/AddBug.vue')['default']
    Assignees: typeof import('./components/Assignees.vue')['default']
    AssignModal: typeof import('./components/Modals/AssignModal.vue')['default']
    AttachmentsItem: typeof import('./components/Attachments/AttachmentsItem.vue')['default']
    AttachmentsList: typeof import('./components/Attachments/AttachmentsList.vue')['default']
    Avatar: typeof import('./components/Avatar.vue')['default']
    BugCard: typeof import('./components/BugCard.vue')['default']
    BugInfo: typeof import('./components/tabs/BugInfo.vue')['default']
    BugList: typeof import('./components/tabs/BugList.vue')['default']
    BugTab: typeof import('./components/tabs/BugTab/index.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    CollapsableList: typeof import('./components/CollapsableList.vue')['default']
    Comments: typeof import('./components/Comments/index.vue')['default']
    DeleteModal2: typeof import('./components/Modals/DeleteModal2.vue')['default']
    DropdownButton: typeof import('./components/DropdownButton.vue')['default']
    Info: typeof import('./components/tabs/BugTab/Info.vue')['default']
    LanguageSwitch: typeof import('./components/LanguageSwitch.vue')['default']
    LoadingModal2: typeof import('./components/Modals/LoadingModal2.vue')['default']
    Marker: typeof import('./components/Marker.vue')['default']
    MarkerList: typeof import('./components/MarkerList.vue')['default']
    Message: typeof import('./components/Comments/Message.vue')['default']
    Modal: typeof import('./components/Modals/Modal.vue')['default']
    ModalTemplate: typeof import('./components/ModalTemplate.vue')['default']
    Overlay: typeof import('./components/Overlay.vue')['default']
    ProjectManager: typeof import('./components/ProjectManager.vue')['default']
    Screenshot: typeof import('./components/tabs/BugTab/Screenshot.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    Spinner: typeof import('./components/Spinner.vue')['default']
  }
}
