// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    LanguageSwitch: typeof import('./components/LanguageSwitch.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    Spinner: typeof import('./components/Spinner.vue')['default']
  }
}
